config/routes.rb
require File.expand_path(File.join(Rails.root, 'api/api.rb'))

Greenarea::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks, :registrations => :"users/registrations", :passwords => :"users/passwords", :sessions => :"users/sessions" }

  root 'home#index'

  resources :subscriptions, only: :create

  resources :projects, except: :destroy do
    resources :investments, only: [:new, :create]
  end

  get 'dashboard' => 'dashboard#index'
  get 'blog' => 'blog#index', as: :blog

  resources :users, only: :show

  devise_scope :user do
    put '/users/upload_images', to: 'users/registrations#upload_images'
  end

  resources :contacts, only: [:new, :create]

  resources :events

  mount GetVersion::Web => '/'
  mount Api => '/api'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role?(:admin)
      can :manage, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

  validates :provider, :uid, :email, :user_id, presence: true

  def self.find_user_by_auth(auth)
    authentication = where(provider: auth.provider).
                     where(uid: auth.uid).
                     where(email: auth.info['email']).
                     first
    authentication.try(:user)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :email, :message, presence: :true, length: { minimum: 4, too_short: "Please enter at least 4 characters" }	
end

app/models/investment.rb
class Investment < ActiveRecord::Base
  mount_uploader :identification_document, IdentificationDocumentUploader

  attr_accessor :state, :country

  belongs_to :user
  belongs_to :project

  has_many :project_investors, through: :project, source: :investors

  validates_numericality_of :quantity, greater_than: 0
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content

  # self.per_page = 6

  mount_uploader :post_image, PostImageUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :investments
  has_many :investors, through: :investments, source: :user, uniq: true

  mount_uploader :image, ImageUploader

  belongs_to :user

  validates :name, :latitude, :longitude, presence: true

  paginates_per 6

  include Addressable

  include PublicActivity::Model
  tracked skip_defaults: true

  def image_url
    image.url(:thumb)
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :email, :uniqueness => true, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :token_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :linkedin]

  attr_accessor :current_password

  validates :email, :status, presence: true

  has_many :investments
  has_many :invested_projects, through: :investments, source: :project, uniq: true

  def investors
    # do not include self
    investments.map(&:project_investors).flatten.uniq - [self]
  end

  def total_invested
    investments.map(&:money).sum
  end

  scope :recent, lambda { |count| order('users.created_at desc').limit(count) }

  def role?(r)
    self.role.to_s == r.to_s
  end

  include SocialAuthentication
  include Addressable
  include Nameable

  include PublicActivity::Model
  tracked skip_defaults: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do
    render :file => "#{Rails.root}/public/404.html", :status => 404
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_url
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @posts = PostsDecorator.decorate(Post.page(params[:page]))
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout false

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])

    if @contact.save
      ContactMailer.new_contact(@contact).deliver
      flash.now[:success] = I18n.t('contacts.create.success')
    else
      flash.now[:errors] = I18n.t('contacts.create.error')
      render :new
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = ProjectsDecorator.decorate(Project.order('created_at desc').all)
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_filter :find_project
  before_filter :authenticate_user!

  def new
    @investment = @project.investments.new
  end

  def create
    investments = InvestmentsCreator.new(current_user, @project)

    if investments.create(params[:investment])
      gflash(success: "Investment was created")
      redirect_to @project
    else
      gflash(errors: "Something went wrong")
      render :new
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id]).decorate
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, only: :show

	def index
    @projects = ProjectsDecorator.decorate(Project.page(params[:page]))
	end

  def show
    # @activities = @project.activities.includes(:user).includes(:trackable).order('created_at desc').limit(15).load
    @investors = @project.investors.load
    @project = @project.decorate
  end

  def new
    @project = Project.new
    render :layout => false
  end

  def create
    project = Project.create!(params[:project])
    redirect_to root_path
  end

  private

  def find_project
    @project = Project.includes(:investors).find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user

  def show
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FacebookShare

  def projects_json(projects)
    projects.to_json(only: [:id, :name, :latitude, :longitude], methods: [:image_url])
  end

  def signature(options = {})
    Base64.encode64(
      OpenSSL::HMAC.digest(
        OpenSSL::Digest::Digest.new('sha1'),
        Rails.configuration.s3.secret,
        policy({ secret_access_key: Rails.configuration.s3.access_key })
      )
    ).gsub(/\n/, '')
  end

  def policy(options = {})
    Base64.encode64( {
      expiration: 30.minutes.from_now.utc.strftime('%Y-%m-%dT%H:%M:%S.000Z'),
        conditions: [
          { bucket: Rails.configuration.s3.bucket },
          { acl: 'public-read' },
          { success_action_status: '201' },
          ['starts-with', '$key', '']
        ]
      }.to_json
    ).gsub(/\n|\r/, '')
  end

  def active_menu_item(item)
    controller_name == item ? "active" : ""
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def projects_json(projects)
    projects.to_json(only: [:id, :name, :latitude, :longitude], methods: [:image_url])
  end

  def user_json(user)
    user.to_json(only: [:latitude, :longitude])
  end
end

app/helpers/home_helper.rb
module HomeHelper
  include ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_json(project)
    project.to_json(only: [:id, :name, :latitude, :longitude], methods: [:image_url])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_user_json(user)
    json = user.as_json(only: [:id, :facebook_link, :twitter_link, :google_plus_link, :linkedin_link], methods: :profile_image)
    json.to_json
  end
end

app/views/projects/_project.html.erb
<div class="example" ng-controller='ProjectController' data-project="<%= project_json(project) %>">
  <h2 class="ui header">
    <%= link_to project.name, project_path(project) %>

    <div class="ui rating">
      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>
    </div>
  </h2>

  <div class="sub header"><%= project.short_description %></div>

  <div class="map-view" ng-class='{tucked:!isOpened}' ng-controller='MapsController' data-markers='<%= projects_json([project]) %>'>
    <div class="map-toolbar-one">
      <div class="show-map ui button" ng-click='show()'>Show map</div>
    </div>

    <div class="map-toolbar-two">
      <div class="show-map ui button" ng-click='close()'>x</div>
    </div>

    <div class="map-viewport">
      <es-google-map options='google.settings' refresh='google.refresh' extra='google.extra' styles='google.styles' style='height: 30rem;display:block;'></es-google-map>
    </div>
  </div>

  <div class="ui celled list">
    <% project.investments.each do |investment| %>
      <div class="item">
        <img src="<%= investment.user.profile_image %>">

        <div class="content">
          <div class="header"><%= link_to investment.user.name, user_path(investment.user) %></div>
          <i>total badged trees: <%= investment.quantity %></i>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class='main container'>
  <h1 class="ui">Projects</h1>
  <%= render @projects %>
</div>

<div class="main container">
  <%= paginate @projects %>
</div>

app/views/projects/new.html.erb
<%= form_for @project, :multipart => true, :html => { :class => "ui test modal transition hidden", :'ng-controller' => 'MarkersController', :'ng-init' => 'init()' } do |f| %>
  <i class="close icon"></i>
  <div class="header">Add new marker to this area</div>
  <div class="content">
    <div class="ui form segment">
        <div class="field">
          <label>Name</label>
          <div class="ui left labeled input">
            <%= f.text_field :name, :'ng-model' => 'project.name', :placeholder => "Name", :'ng-required' => 'true' %>

            <div class="ui corner label">
              <i class="icon asterisk"></i>
            </div>
          </div>
        </div>

        <div class="field">
          <label>Description</label>
          <div class="ui left labeled icon input">
            <%= f.text_area :description, :'ng-model' => 'project.description', :placeholder => 'Description', :'ng-required' => true %>

            <div class="ui corner label">
              <i class="icon asterisk"></i>
            </div>
          </div>
        </div>

      <div class="field">
        <label>Photo</label>
        <div class="ui left labeled icon input">
          <%= f.file_field :image %>
          <i class="lock icon"></i>
          <div class="ui corner label">
            <i class="icon asterisk"></i>
          </div>
        </div>
      </div>

      <%= f.hidden_field :latitude %>
      <%= f.hidden_field :longitude %>

      <div class="ui error message">
        <div class="header">We noticed some issues</div>
      </div>
    </div>
  </div>

  <div class="actions">
    <div class="ui black button">
      Cancel
    </div>
    <input type='submit' class="ui green right labeled icon button" ng-class='{disabled:form.$invalid}'>
      <i class="checkmark icon"></i>
    </div>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="main container">
  <div class="example" ng-controller='ProjectController' data-project="<%= project_json(@project) %>">
    <h1 class="ui">
      <%= @project.name %>

      <% if current_user.present? %>
        <div class="ui teal labeled icon button">
          Invest 5$
          <i class="add icon"></i>
        </div>
      <% end %>

    </h1>
    <div class="ui huge star rating active">
      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>
      <i class="icon active"></i>
    </div>

    <div class="sub header"><%= @project.short_description %></div>

    <div class="map-view" ng-class='{tucked:!isOpened}' ng-controller='MapsController' data-markers='<%= projects_json([@project]) %>'>
      <div class="map-toolbar-one">
        <div class="show-map ui button" ng-click='show()'>Show map</div>
      </div>

      <div class="map-toolbar-two">
        <div class="show-map ui button" ng-click='close()'>x</div>
      </div>

      <div class="map-viewport">
        <es-google-map options='google.settings' refresh='google.refresh' extra='google.extra' styles='google.styles' style='height: 30rem;display:block;'></es-google-map>
      </div>
    </div>

    <div class="ui celled list">
      <% @project.investments.each do |investment| %>
        <div class="item">
          <img src="<%= investment.user.profile_image %>">

          <div class="content">
            <div class="header"><%= investment.user.name %></div>
            <i>total badged trees: <%= investment.quantity %></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= render "comments/form" %>
</div>

app/views/public_activity/project/_user_invested.html.erb
<% project = activity.trackable %>
<% user = activity.owner %>

<li>
  <div class="profile-badge">
    <div>
    <a href="<%= project_path(project) %>" title="<%= project.name %>"><img src="<%= project.image.url(:thumb) %>" /></a>
      <div class="focus"></div>
    </div>
  </div>
  <div class="entry">
    <h5 class="entry-title">
      <a href="<%= project_path(project) %>"><%= project.name %></a> invested by <a href="<%= user_path(user) %>"><%= user.name %></a>
    </h5>
    <div class="entry-meta">
      <time><%= distance_of_time_in_words_to_now(a.created_at) %></time>
    </div>
  </div>
</li>